### ISSUE TITLE
Setup Fails: Exception_DB: Database Query Failed

### ISSUE THREAD

**Issue by niccolox** [romaninsh/dokku-alt-manager#12]
is there an undocumented config step for setup?

I simply cant get the dam to connect to the db

Exception_DB: Database Query Failed

```
pdo_error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dam.user' doesn't exist
mode: select
params:
query: select count(*) from `user`
template: select [options] [field] [from] [table] [join] [where] [group] [having] [order] [limit]
```

I've manged to install Wordpress with a mariadb linked ok and set the environment variables

but no joy with dam and dokku-alt

ssh dokku@$HOST create dam
ssh dokku@$HOST mariadb:create dam
ssh dokku@$HOST mariadb:link dam dam

git remote add deploy dokku@$HOST:dam
git push deploy master

ssh dokku@$HOST config:set dam DATABASE_URL='mysql2://dam:hjdhdhjdjdflll@mariadb:3306/dam'

I feel like an idiot, perhaps I've borked my set-up, am new to dokku-alt and dokku-alt-manager

**Comment by jamespacileo** [comment]
I've just installed manager from the dokku-alt-manager git repository... getting the same error.

I'm running dokku-alt beta. Anything I can do to help?

**Comment by niccolox** [comment]
fresh install, same error

**Comment by philipheinser** [comment]
Same here
```
dokku run dam "php bootstrap.php"
Bootstrapping Dokku-alt-manager
Connecting do database: OK
Updating Database: ==[ Exception_DB: Database Query Failed ]===========

Additional information:
 * pdo_error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dam._db_update' doesn't exist
 * mode: select
 * params:   * :a: dokku-alt-000.sql

 * query: select  `status` from `_db_update`  where `name` = :a    
 * template: select [options] [field] [from] [table] [join] [where] [group] [having] [order] [limit]
```

**Comment by ingro** [comment]
Same problem here...

**Comment by eugeneware** [comment]
Yes. Just did a clean install on 14.04 and got the same error.

**Comment by karlcoelho** [comment]
Same error here. Any fix?

**Comment by rusintez** [comment]
+1

**Comment by steviee** [comment]
I finished installation with this step:

After the bootstrapping failed I connected to the mariadb instance with 

dokku mariadb:console dam dam

Then I created the _db_update table manually with this command: 

create table _db_update (id bigint auto_increment primary key, name nvarchar(100), status nvarchar(100));

And exit;

After this I executed the bootstrapper again with this:

dokku run dam "php bootstrap.php"

That's it. Running!

Best regards,
Steviee

**Comment by leejefon** [comment]
@steviee You saved my day!
