### ISSUE TITLE
Creating a DB link did not create config variables

### ISSUE THREAD

**Issue by rchrd2** [romaninsh/dokku-alt-manager#15]
I was scratching my head wondering why the database wasn't working. 
I ended up having to do it from the CLI.
```
dokku config djangodokku
dokku postgresql:create db2
dokku postgresql:link djangodokku db2
dokku config djangodokku
=== djangodokku config vars ===
DATABASE_URL:  postgres://djangodokku:asdf@postgresql:5432/pg2
```
It would be great for this to work with the GUI!

**Comment by romaninsh** [comment]
This looks more like a dokku-alt issue rather then dokku-alt-manager.
