### ISSUE TITLE
Base table or view not found: 1146 Table 'dam._db_update' doesn't exist

### ISSUE THREAD

**Issue by NicolasRitouet** [romaninsh/dokku-alt-manager#21]
After installing Dokku-alt, I install DAM on Digital Ocean (fresh droplet with Ubuntu 14.04 x64) and I get the following error:
```
Bootstrapping Dokku-alt-manager
Connecting do database: OK
Updating Database: ==[ Exception_DB: Database Query Failed ]===========

Additional information:
 * pdo_error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dam._db_update' doesn't exist
 * mode: select
 * params:   * :a: dokku-alt-000.sql

 * query: select  `status` from `_db_update`  where `name` = :a
 * template: select [options] [field] [from] [table] [join] [where] [group] [having] [order] [limit]
````

Going on dam.hostname.com displays:
````
Exception_DB: Database Query Failed
Additional information:

pdo_error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dam.user' doesn't exist
mode: select
params:
query: select count(*) from `user`
template: select [options] [field] [from] [table] [join] [where] [group] [having] [order] [limit]
````
I installed dokku-alt with this command `bash -c "$(curl -fsSL https://raw.githubusercontent.com/dokku-alt/dokku-alt/master/bootstrap.sh)"` and DAM with a simple `dokku manager:install`, nothing else in between.

Have I missed something?

Thanks.
Here're more infos:
DB is empty:
```
MariaDB [dam]> show tables;
Empty set (0.00 sec)
```
Rerunning only the migration script doesn't seem to solve the issue:
```
root@hotname:~# dokku run dam "php bootstrap.php"
Bootstrapping Dokku-alt-manager
Connecting do database: OK
Updating Database: ==[ Exception_DB: Database Query Failed ]===========

Additional information:
 * pdo_error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'dam._db_update' doesn't exist
 * mode: select
 * params:   * :a: dokku-alt-000.sql
```
Anything else I could try?

**Comment by johnnye** [comment]
Looks like a similar issue to: https://github.com/romaninsh/dokku-alt-manager/issues/12

**Comment by pcragone** [comment]
Any updates on resolving this? Encountering the same problem here.

**Comment by HokieTT** [comment]
Quick and dirty, so no promises since I have never run dokku-alt or even dokku until just now:

$ dokku mariadb:console dam dam
MariaDB [dam]> CREATE TABLE _db_update (status varchar(255), name varchar(255));
MariaDB [dam]> exit
$ dokku manager:upgrade

Works for me now.

**Comment by xypaul** [comment]
@HokieTT that fixed it for me. Thanks :+1:

**Comment by buzzlightyear182** [comment]
@HokieTT Used your solution, thanks! :)

**Comment by claudyus** [comment]
This bug affect also my newly installation and @HokieTT woekaround the problem.

**Comment by bkenny** [comment]
@HokieTT ❤️

**Comment by micku** [comment]
Same bug for me, thank you so much @HokieTT!!

**Comment by NicolasRitouet** [comment]
It seems I'm not the only one having the issue.
Can we try to solve this definitively?
I'll try to take a deeper look at the code this evening, but I found the line that should create the table `_db_update`:  
https://github.com/romaninsh/dokku-alt-manager/blob/2e89b5ca55eb803c3d74b63a95734f7b2804a936/shared/lib/Controller/Migrator/MySQL.php#L16 ?

**Comment by plitex** [comment]
I've had the same problem and thanks to @HokieTT is fixed! Thanks!

**Comment by NicolasRitouet** [comment]
I've sent a PR to fix this:
https://github.com/romaninsh/dokku-alt-manager/pull/22
The solution I implemented may not be the best one, but at least, we have the root cause of the problem, @romaninsh can choose the best solution to fix this.

**Comment by brunowego** [comment]
@HokieTT :+1: Thanks!

**Comment by Saren-Arterius** [comment]
@HokieTT <3

**Comment by romaninsh** [comment]
This have been merged. Please see if it resolves the issue.

**Comment by NicolasRitouet** [comment]
@romaninsh can you send a PR to the upstream branch (https://github.com/dokku-alt/dokku-alt-manager) so, that this command `dokku manager:install` works out of the box?

**Comment by patrick-mota** [comment]
Still having the problem..
I just did the "dirty trick":
$ dokku mariadb:console dam dam
MariaDB [dam]> CREATE TABLE _db_update (status varchar(255), name varchar(255));
MariaDB [dam]> exit

And it works, (well the error was explicit _db_update missing...) thank you

**Comment by tlongren** [comment]
Having this problem as well on each Ubuntu 14.04 VM I've tried it on.

Solution from @HokieTT works. :+1:

**Comment by Chris2048** [comment]
Please integrate solution into a bugfix, Thanks :-)

**Comment by tlongren** [comment]
I'll take care of it.

**Comment by NicolasRitouet** [comment]
> Please integrate solution into a bugfix, Thanks :-)

There is one, it just needs to be merged to the fork from dokku-alt that's used when you do `dokku manager:install`
https://github.com/dokku-alt/dokku-alt-manager/pull/1

**Comment by tlongren** [comment]
So just waiting for someone to merge it??

**Comment by NicolasRitouet** [comment]
Well, dokku-alt is not using this repo for dokku-alt-manager, but this fork:
https://github.com/dokku-alt/dokku-alt-manager
I created the PR to pull the changes from upstream (this repo).
I just sent a mail to @ayufan to ask him to merge the PR.
Let's see what happens.

**Comment by iDev0urer** [comment]
Still getting this issue, but @HokieTT 's solution worked

**Comment by mcneela86** [comment]
@HokieTT solution worked for my, had to run 'dokku manager:upgrade' after it to get the dashboard working.
